# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  quick_colors: "" # select quick color schemes: "blue", "green", "orange", "pink", "purple", "red". If empty colors taken from _sass/ryancv/settings.scss
  dark_ui: 0 # activated dark ui styles
  rtl: 0 # activated rtl styles
  sidebar: 1 # for disable sidebar and sidebar button change to 0
  preloader: "loading..." # preloader loading text

### Portfolio Filters Settings
portfolio:
  filters:
    - name: "All"
      slug: "box-item"
      active: 1

    - name: "UI/UX Design"
      slug: "f-design"
      active: 0

    - name: "Research"
      slug: "f-research"
      active: 0

    - name: "Development"
      slug: "f-dev"
      active: 0


